### ISSUE TITLE
Define icon strategy for elements release

### ISSUE THREAD

**Issue by shinytoyrobots** [IBM/carbon-elements#10]
This issue might potentially be an umbrella for coordinating a variety of work that needs to be done for the icons package under the elements release. Ideally, we'd do the following:

- [x] Define our icon strategy, from padding box to artboard sizes
- [x] Verify https://github.ibm.com/carbon/issues/issues/878 (internal) is resolved
- [ ] ~Create a Sketch artifact with icons supporting the sizes decided above~ Manual created by design
- [ ] ~Create a box folder with all delivered icons found in the Sketch file above~ Icons now live in GitHub repo
- [ ] Migrate icons over to the icons package under carbon elements
- [x] Update build process to include new sizes
- [ ] Create contribution docs for design
- [ ] Create contribution docs for development
- [ ] Polish package and use it in `carbon-icons`
- [ ] Design updated iconography page with new icons
- [ ] Build iconography page

**Comment by joshblack** [comment]
cc @chrisconnors-ibm for details from design perspective

**Comment by joshblack** [comment]
cc @jeanservaas @chrisconnors-ibm to help plan our strategy here for:

- Figuring out where the icons are stored in Box
- Determining sizes
- Determining strategy around extra padding in icon artboard

**Comment by chrisconnors-ibm** [comment]
I would prefer they never live on box but rather in a repository.
We have 16x16 glyphs and 32x32 icons.
there is no 'extra' padding since artwork occasionally intrudes there.

**Comment by joshblack** [comment]
Makes sense @chrisconnors-ibm! 

> I would prefer they never live on box but rather in a repository.

I only meant Box so that I had a link handy to bring things over 👍 

> We have 16x16 glyphs and 32x32 icons.

Is there a 24x24 size that we are looking to support, or no?

> there is no 'extra' padding since artwork occasionally intrudes there.

And cool! Sounds good 👍

**Comment by aagonzales** [comment]
In the current Carbon system we do not support 24x24 (before V9 we did though).
