### ISSUE TITLE
Icon Visual Bugs

### ISSUE THREAD

**Issue by joshblack** [IBM/carbon-elements#102]
Figured we could use this issue to keep track of all the visual-related bugs for icons.

- [`16/add--filled`](https://carbon-elements.netlify.com/icons/examples/esm/#16%2Fadd--filled)
- `32/menu` downsized to 20 https://carbon-elements.netlify.com/icons/examples/esm/#32%2Fmenu%20Downsized%20to%2020

**Comment by chrisconnors-ibm** [comment]
menu is tracked here: https://github.com/IBM/carbon-elements/issues/121
