### ISSUE TITLE
New type tokens

### ISSUE THREAD

**Issue by eraymond25** [IBM/carbon-elements#104]
**Is your feature request related to a problem? Please describe.**
The type tokens have been redone

**Describe the solution you'd like**
An update to the component, editorial layout and product layout tokens detailed out here: https://ibm.box.com/s/igvyfkpawrp0l0hm0mbyg1sdifeplpir

**Describe alternatives you've considered**
All the variations in the past

**Additional context**
Make in conjunction with Anna, Jeannie and Wonil. Should be completed before the v10 release

**Comment by joshblack** [comment]
@aagonzales is there a design issue to finalize the naming before we should start updating on the dev side?

**Comment by eraymond25** [comment]
slight edit to above: "only headers **04-05** are prefixed with productive or expressive"
