### ISSUE TITLE
Create @carbon/type package for Carbon Elements

### ISSUE THREAD

**Issue by shinytoyrobots** [IBM/carbon-elements#11]
This issue is for introducing the `@carbon/type` package to the Carbon Elements monorepo on public GitHub. This package will use the [type package](https://github.ibm.com/carbon/duo-monorepo/tree/master/packages/type) from the duo monorepo as it's base, and then will consume updates from the decisions in #961.

At a high-level, we're hoping that this package supports the following use-cases:

- Supports including the generated CSS of the project in a page and having it work by-default
- Supports including the generated SCSS in a development project's SCSS
- Supports including the source JS in a development project's CSS-in-JS solution

General support in this case will mean the following:

- Sensible global styles that are opt-in by default, but can be excluded from the bundle if needed
- Ability to access font family information
- Ability to incorporate a font loading strategy in their project
- Ability to apply specific scale entries in the type scale in the target project language (CSS, SCSS, JS)

This work also should take into account theming, and should export the default theme (product) in addition to the editorial theme.

**Comment by joshblack** [comment]
Final specs: https://github.com/carbon-design-system/issue-tracking/issues/27#issuecomment-422920858
