### ISSUE TITLE
[Layout] Argument `$map` of `map-get($map, $key)` must be a map

### ISSUE THREAD

**Issue by jendowns** [IBM/carbon-elements#118]
### Describe in detail the issue you're having.

I'm importing the grid (`0.0.1-alpha.20`) and layout (`0.0.1-alpha.20`) packages into our scss like so:
```
@import '@carbon/layout/scss/layout';
@import '@carbon/grid/scss/grid';
```
And I'm applying those styles to our Storybook.

However, whenever I try to `start-storybook`, I get the following build error: 
```bash
ERROR in ./node_modules/css-loader??ref--6-1!./node_modules/postcss-loader/lib!./node_modules/sass-loader/lib/loader.js??ref--6-3!./.storybook/Container/_index.scss
Module build failed:
    $map: map-get($map, $key);
         ^
      Argument `$map` of `map-get($map, $key)` must be a map
      in /Users/jendowns/project/node_modules/@carbon/layout/scss/_utilities.scss (line 9, column 11)
```

Have you all experienced this  issue on your end?

Some extra dependency info:
```
"@storybook/react": "^3.3.14",
"css-loader": "^0.28.10",
"style-loader": "^0.20.2",
"postcss-loader": "^2.1.1",
```

### What version of the Carbon Design System are you using?

We are using:
```
"@carbon/grid": "^0.0.1-alpha.20",
"@carbon/layout": "^0.0.1-alpha.20",
"carbon-components": "^9.59.0",
"carbon-components-react": "^6.55.5",
```

## Steps to reproduce the issue

1. Add `@import '@carbon/layout/scss/layout';` to your scss (in a Storybook environment)
2. Run `start-storybook`

**Comment by joshblack** [comment]
Ugh this is probably an issue with `map-deep-get`. Had similar woes with `carbon-components`. Could you try updating these calls:

```
    $width: map-deep-get($breakpoints, $breakpoint, width);
    $margin: map-deep-get($breakpoints, $breakpoint, margin);
    $columns: map-deep-get($breakpoints, $breakpoint, columns);
```

To just nested `map-get` calls to see if it helps?

**Comment by jendowns** [comment]
Thanks @joshblack! 

So just a quick note: I updated this title and issue to better reflect what is actually going on at the moment. Originally, I was seeing that null error because I was importing an older scss file elsewhere. But now that's been taken care of.

So just to repost what I edited above, my error with the current `map-deep-get` is this:
```
ERROR in ./node_modules/css-loader??ref--6-1!./node_modules/postcss-loader/lib!./node_modules/sass-loader/lib/loader.js??ref--6-3!./.storybook/Container/_index.scss
Module build failed:
    $map: map-get($map, $key);
         ^
      Argument `$map` of `map-get($map, $key)` must be a map
      in /Users/jendowns/project/node_modules/@carbon/layout/scss/_utilities.scss (line 9, column 11)
```

I tried replacing those `map-deep-get` lines with the following:
```
$currentBreakpoint: map-get($breakpoints, $breakpoint);
$width: map-get($currentBreakpoint, width);
$margin: map-get($currentBreakpoint, margin);
$columns: map-get($currentBreakpoint, columns);
```

Which changed my error to this:
```
ERROR in ./node_modules/css-loader??ref--6-1!./node_modules/postcss-loader/lib!./node_modules/sass-loader/lib/loader.js??ref--6-3!./.storybook/Container/_index.scss
Module build failed:
    $width: map-get($currentBreakpoint, width);
           ^
      Argument `$map` of `map-get($map, $key)` must be a map
      in /Users/jendowns/project/node_modules/@carbon/layout/scss/_key-height.scss (line 18, column 13)
```

Moreover, when I `@debug: $currentBreakpoint` at this point, I get values like `(width: 99rem, columns: 16, gutter: 1rem, margin: 1rem)`, which seem correct 🤔

**Comment by joshblack** [comment]
I think we ended up resolving this, right @jendowns? Was a random breakpoint that wasn't coming from layout.

Action item on our end will be to guard our key-heights helper, I think, so that we don't rely on an implicit breakpoints being available.

**Comment by jendowns** [comment]
Yup, thanks for the help! 🎉

**Comment by joshblack** [comment]
Going to re-open this so we can track that bugfix upstream too!

**Comment by jendowns** [comment]
Thanks @joshblack! So for now I believe I can work around this, but just some extra info:

I'm not importing any old layout or grid stylesheets directly, but I can confirm that those old problematic breakpoints are coming through one of the component stylesheets we are importing.

**Comment by joshblack** [comment]
@jendowns good point. We can toggle grid imports based on that feature flag, which I'll make an issue to do 👍
