### ISSUE TITLE
Verify usage of colors and interaction colors for elements

### ISSUE THREAD

**Issue by shinytoyrobots** [IBM/carbon-elements#12]
This issue is for verifying our usage of the color palette and interaction palette for the colors we're looking to ship in our elements release. We have a couple of questions that will need to be resolve and documented. For reference, here's what is meant by the color palette and interaction colors:

![image](https://user-images.githubusercontent.com/825457/45527134-c1912c80-b79f-11e8-9658-64972ac7bb09.png)

On the left hand side of the screen, we see the color palette. On the right, we see the beginning of the hover palette. The convention (I believe) is to use the corresponding color for the interaction state you expect the node to transition to. For example, if something is blue 60 and it is being hovered, you would go to the hover palette and choose blue 60. There are a variety of colors available for these interaction states:

![image](https://user-images.githubusercontent.com/825457/45527140-c7870d80-b79f-11e8-93c9-3a35365a5ad8.png)

Here's what most likely needs to be decided:

- Verify the final palette for colors
  - For artifacts, having a sketch deliverable would be great. If we structure the sketch file appropriately, we could also auto-generate the colors from the sketch file
- Decide on the pattern we will follow for interaction colors
  - For example, are we using the interaction colors? If so, what patterns/guidance can we provide? What will they be named?
  - If not, what convention will we use instead?

Feel free to edit this list with anything else that might need to be decided!

**Comment by joshblack** [comment]
cc @jeanservaas for colors

**Comment by joshblack** [comment]
Blocked waiting for final specs here for colors package

**Comment by eraymond25** [comment]
[IBM Duo UI Palette – Beta V06@2x.pdf](https://github.com/IBM/carbon-elements/files/2417094/IBM.Duo.UI.Palette.Beta.V06.2x.pdf)
here are the correct v06 colors that we're using on Digital

**Comment by aagonzales** [comment]
@dinaerdianinque - assigned

**Comment by shixiedesign** [comment]
Coming back to this work, here's what I gather to be state of things: 
- We want to programmatically generate interaction colors (hover, active, select), aka users will not be exposed these interaction colors, nor have the ability to edit them. 
- There's concern over efficiency because users might have to download more code

**Comment by aagonzales** [comment]
Proposed solution:interaction state color tokens, each color is just a single hex. Does this work?

# Interaction State Tokens

Token | White Theme Value | Usage
-- | -- | --
$focus* | Blue 60 | Focus border <br /> Focus underline
$hover-primary | Blue 60 Hover | Hover color for brand-01
$active-primary* | Blue 80 | Active color for brand-01
$hover-primary-text | Blue 70 | Text + icon hover color for brand-01
$hover-secondary | Gray 100 hover | Hover for ui-05
$active-secondary* | Gray 80 | Active-background for ui-05
$hover-ui* | Gray 10 Hover #e5e5e5e | hover white elements <br /> hover Gray elements <br /> hover transparent elements
$active-ui* | Gray 30 | Active background color for ui-01
$hover-danger | Red 60 Hover / #ba1b23 | Support-01 hover
$active-danger* | Red 80 | Active color for support-01
$hover-row | TBD | Row hover
$visted-link* | Purple 60 | Visited state for link
$disabled-01* | Gray 10 | disabled fields background <br /> disabled backgrounds <br />disabled border
$disabled-02* | Gray 30 | disabled elements on $disabled-01 (Gray 10) <br /> disabled label on $disabled-01 (Gray 10) <br /> disabled text on $disabled-01 (Gray 10) <br /> disabled icons on $disabled-01 (Gray 10) <br /> disabled border <br /> disabled background
$disabled-03* | Gray 50 | disabled text on $disabled-02 (Gray 30) <br /> disabled icon on $disabled-02 (Gray 30)

**Comment by aagonzales** [comment]
Closing, using tokens assigned by usage instead of individual hex codes.
