### ISSUE TITLE
Verify type scale and styles for `carbon-elements`

### ISSUE THREAD

**Issue by shinytoyrobots** [IBM/carbon-elements#13]
This issue is for design to sign-off on the existing type scales and styles for the IDL refresh that's making it's way into our OSS `carbon-elements` project.

The current set of styles for both projects are currently at:

- [IDL Refresh](https://duo.w3ibm.mybluemix.net/elements/type-specs/#type-set) (internal)
- [Carbon Design System](http://carbondesignsystem.com/style/typography/type-styles)

Some of the differences that we need to settle on or confirm:

- [ ] Type scale naming conventions
  - Do we use an alphabet scale, greek, phonetic, etc
  - Do we need custom steps for font families? Like Type A Mono
  - How should we differentiate "tight" options, like Type B and Type B Tight
- [ ] Type scale styles
  - Verify the specs match what needs to be in OSS
  - Verify that responsive specs match the needs that we have
  - Verify whether things like margin (top/bottom) should be specified on these type styles

**Comment by shinytoyrobots** [comment]
Extensive discussion of this issue at https://github.ibm.com/carbon/issues/issues/961 (internal)

**Comment by joshblack** [comment]
Closing in favor of https://github.com/carbon-design-system/issue-tracking/issues/27, although ideally these issues should be on this repo 👍 Only reason is that the conversation is happening over in that one.
