### ISSUE TITLE
Remove `ibm` prefixes from variables or selectors

### ISSUE THREAD

**Issue by joshblack** [IBM/carbon-elements#135]
Since part of the goals of this project are to be brand-agnostic, we should try and tie the naming here to the system instead of referring to a specific company.

**Comment by cal-smith** [comment]
We've had an issue open for a while on the angular repo - https://github.com/IBM/carbon-components-angular/issues/51

I guess the biggest question is - to what? For selectors I'd propose just `c` (`c-dropdown`, `c-icon-add32`). 

When we originally went with `ibm` I know there was some talk of re-branding carbon ... As I understand it we're doubling down on the carbon brand instead, so it makes sense to unify the naming.

**Comment by joshblack** [comment]
@cal-smith good question! We'll find out soon, hopefully 😄 can sync up on Slack if you want to talk about it more!
