### ISSUE TITLE
Export scss color map for colors

### ISSUE THREAD

**Issue by jendowns** [IBM/carbon-elements#136]
## Context 

In the old internal color package we are using, we have a useful scss color map that is exported along with all of the color variables, structured like this:

```
$ibm-color-map: (
  'blue': (
    10: $ibm-color__blue-10,
    20: $ibm-color__blue-20,
    30: $ibm-color__blue-30,
    40: $ibm-color__blue-40,
    50: $ibm-color__blue-50,
    60: $ibm-color__blue-60,
    70: $ibm-color__blue-70,
    80: $ibm-color__blue-80,
    90: $ibm-color__blue-90,
    100: $ibm-color__blue-100,
  ),
'cool-gray': (
    10: $ibm-color__cool-gray-10,
    20: $ibm-color__cool-gray-20,
    30: $ibm-color__cool-gray-30,
    40: $ibm-color__cool-gray-40,
    50: $ibm-color__cool-gray-50,
    60: $ibm-color__cool-gray-60,
    70: $ibm-color__cool-gray-70,
    80: $ibm-color__cool-gray-80,
    90: $ibm-color__cool-gray-90,
    100: $ibm-color__cool-gray-100,
  ),

 ...

);
```

It's very useful for us because we mix some colors in a few scss function and use steps, etc. So the map allows us to quick access a color by step and then manipulate it.

### Request

Can you all add a color map with your exported scss, structured similarly to the example above, so we can use it in our existing scss functions? 🙏 😅

**Comment by joshblack** [comment]
@jendowns want to do a PR real quick for `$ibm-colors` support? Just need to append it when we generate the colors source code in: https://github.com/IBM/carbon-elements/blob/275a5eec55fb6f80670047e60348e66a6b7eb161/packages/colors/src/build.js#L28 I think

**Comment by jendowns** [comment]
@joshblack yeah I can do that! 👍

**Comment by jendowns** [comment]
@joshblack what do you think I should do with the 2 colors that don't have grades? Black and white? 🤔 

In the old colors package, their variables have grades (i.e., `$ibm-color__black-100`) and their entries in the color map also include their grades:

```
'black': (
    100: $ibm-color__black-100,
  ),
'white': (
    0: $ibm-color__white-0,
  ),
```

The two solutions that come to mind... either do something very special for black & white, or just leave them out of the map. 😅 Thoughts?

**Comment by vpicone** [comment]
@joshblack is there a reason the ungraded colors aren't tokens? Moving them there could allow for a much more unified `colors` object with individual colors having graded properties. Having graded/ungraded colors in the colors object could imply there's a black10 black20 etc.

Could make the sass build more straightforward as well.

**Comment by jendowns** [comment]
@vpicone good question -- here's some additional context I just wanted to reiterate:

Our old internal color package used `black100` and `white0` (no other grades for those colors) and those 2 colors were provided in the map along with the other color grades. So it would be nice to continue to include those for the sake of continuity.

**Comment by vpicone** [comment]
@jendowns that make sense! I was wondering if it would just make more sense to store the actual colors as a map you mentioned for the color map or if there's some reason for naming them as they are now with the color name combined with the grade.

```
export const colors = {
  black: { 0: '#000000' },
  white: { 100: '#ffffff' },
  'cool-grey': {
    10: '#fff0f1',
    20: '#fcd0d3',
    30: '#ffa4a9',
    40: '#ff767c',
    50: '#fb4b53',
    60: '#da1e28',
    70: '#a51920',
    80: '#750e13',
    90: '#570408',
    100: '#2c080a'
  }
```

**Comment by joshblack** [comment]
@vpicone really the only significant reason they aren't considered tokens is that we don't use color names in token names, although clearly white/black might be an exception 😂 We try and keep token names usage-inspired (interactive-01, text-01, etc)
