### ISSUE TITLE
carbon/grid build reporting invalid CSS value

### ISSUE THREAD

**Issue by techtolentino** [IBM/carbon-elements#137]
## Detailed description

> I'm trying to add the newest `@carbon/grid` package to an older project. I added `@carbon/import-once`, `@carbon/layout`, and `@carbon/grid` to the dependencies. 
>
> Now, when attempting to `@import` into my `main.scss` file, I'm Gulp is throwing an error, stating the following:  

```
Error: 1px*rem isn't a valid CSS value.
        on line 29 of node_modules/@carbon/grid/scss/_container.scss, in mixin `@content`
        from line 149 of node_modules/@carbon/layout/scss/_breakpoint.scss, in mixin `@content`
        from line 88 of node_modules/@carbon/layout/scss/_breakpoint.scss, in mixin `breakpoint-up`
        from line 148 of node_modules/@carbon/layout/scss/_breakpoint.scss, in mixin `breakpoint`
        from line 28 of node_modules/@carbon/grid/scss/_container.scss, in mixin `make-container`
        from line 9 of node_modules/@carbon/grid/scss/grid.scss
        from line 56 of app/scss/main.scss
>>         padding-left: #{($grid-gutter / 2) + $margin};
```

## Steps to reproduce the issue

1. Fork and clone https://github.ibm.com/security/design-guide (optional)
2. `npm install` the `import-once`, `grid`, and `layout` packages
3. add `@import '@carbon/grid/scss/grid.scss';` to the main.scss file
4. `npm run dev`

## Additional information

**Note:** I also attempted to `includePaths` so that the gulp-sass plugin can attempt to find sub-dependencies as well (image attached below), but it seems like the grid.scss file cannot find its own dependency (breakpoint.scss)?

Last note: 🙏 while I don't expect anyone to actually go through these steps, _any_ help/hint on how to get the grid working in this project would be greatly appreciated.

![screen shot 2018-12-10 at 3 07 59 pm](https://user-images.githubusercontent.com/6276074/49761708-6fbc4d80-fc8d-11e8-9dec-2e02e665b1af.png)

**Comment by joshblack** [comment]
@techtolentino want to pair up on this sometime this week to figure out what's going on?

**Comment by techtolentino** [comment]
@joshblack - thanks for your help - we can close this issue!

For the record, if anyone is experiencing something similar, the solution was with the import order. Moving the `@carbon/grid` sass import to the top helped solve the issue.
