### ISSUE TITLE
Create @carbon/layout package (and potentially @carbon/grid)

### ISSUE THREAD

**Issue by joshblack** [IBM/carbon-elements#16]
- Design
  - [ ] Get latest sketch file for Grid
  - [ ] Get concepts from layout page that should be expressed in code
    - [ ] Mini-unit -> `get-fixed-size`, anything else?
- Development
  - [ ] Create `@carbon/layout` package
  - [ ] Create initial `prefix--grid` class and helpers for layouts, matching spec
  - [ ] Add entrypoints for 12 and 16 columns
  - [ ] Add support for no-padding variants

**Comment by joshblack** [comment]
cc @jeanservaas do you have the sketch file link handy for the grid specs? Also, is there any guidance from the layout page that we should include as code in this pass?

For the specs, would love to use the file that has the visual style presented here:

![screen shot 2018-09-04 at 5 04 14 pm](https://user-images.githubusercontent.com/3901764/45634575-56c64680-ba68-11e8-9987-d735d95088ee.png)

**Comment by jeanservaas** [comment]
Here's is the latest Code page for the grid (.sketch file below)  

Also, between Pete, Chiu and I, we decided to add two new spacers (80 and 96) to the set of basic increments. That's all I have for now, I need to get back to the Layout page after I finish clearing some components for Chris F.

![screen shot 2018-09-17 at 11 01 39 am](https://user-images.githubusercontent.com/43144260/45634861-1915ed80-ba69-11e8-8705-74e8e55db3bc.png)


[Duo_Grid_page_0904_Code_cpc (1).sketch.zip](https://github.com/IBM/carbon-elements/files/2389315/Duo_Grid_page_0904_Code_cpc.1.sketch.zip)

**Comment by joshblack** [comment]
Resources to leverage:

- [Bootstrap Grid](https://getbootstrap.com/docs/4.0/layout/grid/#)
  - https://github.com/twbs/bootstrap/blob/v4-dev/scss/_variables.scss
  - https://github.com/twbs/bootstrap/blob/v4-dev/scss/_grid.scss
  - https://github.com/twbs/bootstrap/blob/v4-dev/scss/mixins/_grid.scss
  - https://github.com/twbs/bootstrap/blob/v4-dev/scss/mixins/_grid-framework.scss
- [SassDoc example](https://github.com/thoughtbot/bourbon/blob/master/core/bourbon/library/_font-face.scss)
