### ISSUE TITLE
import-once: Request for disabling duplicate import error by default

### ISSUE THREAD

**Issue by asudoh** [IBM/carbon-elements#175]
**Is your feature request related to a problem? Please describe.**

An attempt to use [`exports` mix-in in `carbon-elements`](https://github.com/IBM/carbon-elements/blob/v0.0.1-alpha.25/packages/import-once/scss/import-once.scss)  from `carbon-components` ended up with an error like `Module `@carbon/type/scss/_classes.scss` has already been imported.` Investigation revealed that [the new error reporting mechanism for duplicate import](https://github.com/IBM/carbon-elements/blob/v0.0.1-alpha.25/packages/import-once/scss/import-once.scss#L23), is [turned on by default](https://github.com/IBM/carbon-elements/blob/v0.0.1-alpha.25/packages/import-once/scss/import-once.scss#L18).

**Describe the solution you'd like**

The error reporting mechanism to be turned off by default.

**Describe alternatives you've considered**

Changing all `@include exports()` calls in `carbon-components`, though:

1. Using the `exports()` mix-in from `carbon-elements` in `carbon-components` will be a breaking change for `carbon-components` users
2. Carbon users expect us to remove duplicate imports automatically (Many applications relies on that)

**Comment by joshblack** [comment]
Where does the duplicate import occur? Definitely understand if it's too aggressive 👍

**Comment by asudoh** [comment]
@joshblack Saw the issue during the effort of IBM/carbon-components#1551, where I tried to [import `@carbon/type/scss/classes` from `_css--typography.scss`](https://github.com/IBM/carbon-components/blob/f96f71cd353e064f0a909dfc4f8f3a2c7abd68cc/src/globals/scss/_css--typography.scss#L12). `_css--typography.scss` is imported from most of the components. I'm temporarily removing [`@import '@carbon/import-once/scss/import-once` line in `_classes.scss`](https://github.com/IBM/carbon-elements/blob/v0.0.1-alpha.25/packages/type/scss/_classes.scss#L8) to get around this.
