### ISSUE TITLE
Colors JS exports break for users who are migrating

### ISSUE THREAD

**Issue by jendowns** [IBM/carbon-elements#179]
## Detailed description

In `@carbon/colors`, colors are exported like this:

```javascript
var colors = {
  red10: '#fff0f1',
  red20: '#fcd0d3',
  red30: '#ffa4a9',
  ...
};

export { colors, tokens };
```

And end users would have to use them like this:

```javascript 
import { colors } from '@carbon/colors';

const example = colors.red10;
```

However, in the old internal colors package, colors are exported like this:
```javascript
module.exports = {
  "red": {
    "10": "#FFF0F1",
    "20": "#FCD0D3",
    "30": "#FFA4A9",
    ...
  },
};
```

And imported/used like this:
```javascript
import { red } from '[INTERNAL-PACKAGE]/colors';

const example = red[10];
```

So I understand that you are also exporting tokens along with `colors`, so there are extra considerations here, but the usage here is very different than what we are using. It's doubly complicated by the fact that the applications we support prefer to use the JS color exports (and don't generally use scss at all), so this breaks for them as well. 

Is it possible to update this implementation to support the implementation from the old package we are migrating from?

**Comment by jendowns** [comment]
What was nice about being able to use this:

```
import { red } from '[INTERNAL-PACKAGE]/colors';

const example = red[10];
```

Was that we could easily make use of that grade in JS. 

But now with color grades included in the color name string like `red10`, we can't easily access those grades. And anything that was previously using those grades breaks.

So if we could update the JS color exports to be more like the old way, with grade surfaced more? So we can access colors by grade like `colors.red[10]`?

**Comment by joshblack** [comment]
@jendowns the `colors.red[10]` bit always felt off for me, it also is a form that we can't tree-shake easily if we had to, which might come up if we have to ship interaction colors. Is it the ordering aspect that is missing? Or just the call signature itself?

**Comment by jendowns** [comment]
@joshblack let me get back to you by tomorrow morning on how our applications are using the colors... I have a feeling it may just be a call signature issue (which is no biggie). I had the note about using the grades in JS above but I'm actually not 100% sure of that yet.

**Comment by diego-codes** [comment]
Howdy! Just chiming in here: I think than `colors.red10` feels a bit odd to me as well, but I can also understand the technical reason why it makes more sense. From my very narrow perspective, I don't have an issue with changing the variable names if it means better overall performance. In my application we don't use the JS variables that much so it's not a huge deal.

**Comment by diego-codes** [comment]
XFE uses the JS variables more heavily because they use styled components. Though because the variables syntax is so standard, I would think refactoring the color usage is pretty straight forward.

**Comment by jendowns** [comment]
Hey @joshblack, thanks for the suggestions -- I finished looking into how our applications are using the old colors API. Going along with what @diego-codes just said, they aren't using colors + grades programmatically... they're just using the colors + grades as variables directly, nothing fancy. So the call signature is different, but we can put that in our migration nodes (and maybe do something as part of that code mod convo we had?)

Anyway, thanks again for the responses! I'm going to go ahead and close this out. We can work with the current API changes. 🎉
