### ISSUE TITLE
type: Request for renaming breakpoint/font-family mix-ins to avoid name conflicts

### ISSUE THREAD

**Issue by asudoh** [IBM/carbon-elements#184]
**Is your feature request related to a problem? Please describe.**

During the effort of incorpoating `@carbon/layout`/`@carbon/type` packages to `carbon-components` repository (IBM/carbon-components#1551), hit problems with Sass build as [`breakpoint` mix-in in `@carbon/layout`](https://github.com/IBM/carbon-elements/blob/v0.0.1-alpha.25/packages/layout/scss/_breakpoint.scss#L154-L158) and [one in `carbon-components`](https://github.com/IBM/carbon-components/blob/master/src/globals/scss/_layout.scss#L37-L47) override each other, and those two variants expect different format in `$breakpoints`/`$grid-breakpoints` variables. Similar problem happened with `@mixin font-family`, too.

**Describe the solution you'd like**

* `@mixin breakpoint` to be renamed to something like `@mixin breakpoint-default`, or removing `@mixin breakpoint`, as it seems to be merely an alias to `@mixin breakpoint-up`
* `@mixin font-family` to be renamed to something like `@mixin use-font-family` or any name other than `font-family`

**Describe alternatives you've considered**

Tried to e.g. [override `@mixin breakpoint` after importing `@carbon/layout` code](https://github.com/IBM/carbon-components/blob/f96f71cd353e064f0a909dfc4f8f3a2c7abd68cc/src/globals/scss/_typography.scss#L8-L22), but such override has to happen wherever we import `@carbon/layout/scss/_breakpoint.scss` directly or indirectly. Also it's hard to create/maintain such abstraction layer wrt how to cleanly choose old/new API paths.

**Comment by joshblack** [comment]
Should be done! 👍
