### ISSUE TITLE
Refactor colors package and its exports

### ISSUE THREAD

**Issue by joshblack** [IBM/carbon-elements#201]
Currently we support the following imports from the color package:

```js
import { colors, tokens } from '@carbon/colors';
```

What we should most likely support:

```ts
type Color = string;
type ColorSwatch = {
  10: Color,
  20: Color,
  // ...
  100: Color,
};
type ColorMap = {
  red: ColorSwatch,
  blue: ColorSwatch,
  // ...
};

import {
  // Color Map
  colors,
  
  // Object with keys as token names and their values
  tokens,
  // string
  brand01,

  // ColorSwatch
  red,
  // string
  red10,
} from '@carbon/colors';
```

In addition, we should export a typedef for the color package, maybe in

**Comment by joshblack** [comment]
cc @jendowns

**Comment by vpicone** [comment]
Is there a reason to export the individual tokens, colorswatches and `red10` off of the default as well as nested? I'm probably missing something but there could be an oppurtunity to do just do something like this:

```
import {
  colors,
    colors/red, // ColorSwatch
      colors/red[10], // Color
    colors/red10, // Color
  tokens, // group
    tokens/brand01 //Color
}
```

Also is supporting the `red10` syntax an imperitive? I think having two separate storys for accessing the colors in a pallete could introduce some convention confusion to projects using this package.

**Comment by joshblack** [comment]
@vpicone one of the use cases that we want to optimize for (I think) would be usage like:

```js
import { interactive01 } from '@carbon/colors';

const Link = styled.a`
  color: ${interactive01};
`;
```

At a high-level, I think we have a couple of use-cases the module has to support:

- Working with colors or tokens programmatically
- Working with a swatch programmatically (meaning that order of the grades matters and should be available)
- Working with a color for a style in CSS

A major design goal of elements packages is to be tree-shakeable, especially if we have additional swatches in the future. This also influences the structure above.

**Comment by jendowns** [comment]
@joshblack Being able to work with colors programmatically would be pretty neat. Going back to my closed issue, it doesn't look like we are *currently* doing that (in JS, I mean). However, it would be a nice-to-have now that we are working on our charts/viz package, so that we could have this option in the future.

**Comment by joshblack** [comment]
@vpicone agreed! That makes sense to me 😄 

The goal here with the named exports is that we can support the following use-cases

- Docs
  - Should be easy to reference the work and display it on a website
- Libraries
  - Should be easy to programmatically create a set of components or themes for a specific piece of tech
- Apps / Prototypes
  - Should be easy to bring in tokens and apply and use as a theme
  - Should be easy to bring in and use color values directly

**Comment by vpicone** [comment]
Nice, that seems great. I wonder if theming come from exporting different sets of tokens from @carbon/colors/themes? Once you guys settle on exactly what you'd like I'd be happy to help with the .d.ts authoring.
