### ISSUE TITLE
Notification X icon huge on mobile

### ISSUE THREAD

**Issue by shixiedesign** [IBM/carbon-elements#212]
Notification X icon is not the correct size on mobile. Mike identified this on Dec 20th.

![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/206d1592-d663-4d18-868a-3ad0ee1a0c44)

**Comment by alisonjoseph** [comment]
This is 100% a website bug.

**Comment by joshblack** [comment]
Sounds good, thanks @alisonjoseph!

**Comment by alisonjoseph** [comment]
Opened a PR to add in all the updated icons, once v10 is live we can remove the hard coded html and it will pull directly from carbon-components. https://github.com/carbon-design-system/carbon-website/pull/637
