### ISSUE TITLE
Set up themes token in code

### ISSUE THREAD

**Issue by shixiedesign** [IBM/carbon-elements#220]
Need a way to do themes so the same set of tokens can take on different values for different themes. 
Here's the lastest tokens by theme: https://github.com/IBM/carbon-elements/issues/53#issuecomment-451190539

**Comment by aagonzales** [comment]
@joshblack if it wasn't obvious we had to add a few additional tokens to met the needs of the themes. They are as follows:
- $interactive-03
- $ui-background
- $text-04
- $hover-tertiary
- $active-tertiary
- removed $overlay-02
