### ISSUE TITLE
`@carbon/icons-react` loader import error

### ISSUE THREAD

**Issue by SimonFinney** [IBM/carbon-elements#226]
## Detailed description

> Describe in detail the issue you're having.

Importing an individual icon into my project throws a loader error - 

```js
ERROR in ./node_modules/@carbon/icons-react/lib/accessibility/20.js
Module parse failed: Unexpected token (9:37)
You may need an appropriate loader to handle this file type.

| var React = _interopDefault(require('react'));
| 
| function Accessibility20({ children, ...rest }) {
|   return React.createElement(
|     'svg',
```

I would expect a loader would not be required to import a React component, or if it is, the appropriate documentation is provided to indicate that.

> Is this issue related to a specific component?

`@carbon/icons-react`

## Additional information

<img width="571" alt="screenshot 2019-01-07 at 11 49 24" src="https://user-images.githubusercontent.com/3846874/50766892-cf008400-1272-11e9-9b8a-a8b4557746cf.png">

**Comment by joshblack** [comment]
Should be fixed by https://github.com/IBM/carbon-elements/pull/195 in v0.0.1-alpha.26, are you seeing this in latest?

**Comment by SimonFinney** [comment]
@joshblack You're right! False alarm, this is resolved - I was going off the `@latest` tag
