### ISSUE TITLE
`@carbon/elements`: 404 not found

### ISSUE THREAD

**Issue by jendowns** [IBM/carbon-elements#227]
## Detailed description

When I run `yarn add @carbon/elements`, I get the following error:

```
error An unexpected error occurred: "https://registry.yarnpkg.com/@carbon%2felements: Not Found".
```

It appears as though the package is not published? I also get a 404 when I try to locate it directly on npmjs -- https://www.npmjs.com/package/@carbon/elements

**Comment by joshblack** [comment]
Hi @jendowns! 👋 `@carbon/elements` isn't published yet, expect to see it in the next release this week 😄

**Comment by jendowns** [comment]
Oh oops, thanks @joshblack! 😅
