### ISSUE TITLE
App switcher future state

### ISSUE THREAD

**Issue by shixiedesign** [IBM/carbon-elements#234]
We need an App switcher that better serves the purpose of navigating users to parent (/design, IDL) and siblings (digital). Current list of links does not communicate the hierarchy and relationship of all linked sites to current site, Carbon. 

Mike mentioned a floating design, and Shixie suggested this earlier design from Chiu: 
![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/6a58f0f5-1dfd-4495-9f6c-e53149996955)

**Comment by joshblack** [comment]
Hi @shixiedesign! 👋 Should this be in the website repo?

**Comment by joshblack** [comment]
Hey @shixiedesign! Went ahead and closed this, I think it should be in the website repo if you want to move it there 😄
