### ISSUE TITLE
'icons-vue' doesn't install through npm

### ISSUE THREAD

**Issue by rodet** [IBM/carbon-elements#236]
# Problem

Installing the node dependencies through `npm install` does not work. Today, my colleague @ZrianinaMariia encountered the same problem as well.

# Details

```shell
0> npm install
npm ERR! path /Users/rodet/Prog/ibm-design/carbon/carbon-vue-example/node_modules/.staging/carbon-components-vue-0c283366/node_modules/@babel/code-frame
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename '/Users/rodet/Prog/ibm-design/carbon/carbon-vue-example/node_modules/.staging/carbon-components-vue-0c283366/node_modules/@babel/code-frame' -> '/Users/rodet/Prog/ibm-design/carbon/carbon-vue-example/node_modules/.staging/@babel/code-frame-770cbf37'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/rodet/.npm/_logs/2019-01-09T10_21_35_452Z-debug.log
0> npm --version
6.4.1
```

Log file:
[2019-01-09T10_21_35_452Z-debug.log](https://github.com/IBM/carbon-elements/files/2740462/2019-01-09T10_21_35_452Z-debug.log)

# Workaround

Use Yarn, which is not yet documented as dependency of this project.

**Comment by joshblack** [comment]
Hi @rodet! Is this for the package itself, or for working on the elements project?

**Comment by rodet** [comment]
This is the relevant (I think) extract of my dependency declaration:
```
{
  ...
  "@carbon/icon-helpers": "0.0.1-alpha.12",
  "@carbon/icons-vue": "^0.0.1-alpha.21",
  ...
}
```

**Comment by rodet** [comment]
As you can see, I also had to add expressively `icon-helpers` to make the whole work.

**Comment by rodet** [comment]
OK so we can close this @joshblack , as you showed me, deleting `package-json.lock`actually did the trick. I'm going to refresh this file in my project, that way the bug should disappear. Looks like a certain set of dependency broke when together. Thanks for the help!!
