### ISSUE TITLE
typeScale is not a function error using SCSS in NextJS

### ISSUE THREAD

**Issue by sstrubberg** [IBM/carbon-elements#237]
## Detailed description

`Node v10.13.0`
`NextJS v7.0.2`
`@carbon/colors 0.0.1-alpha.12`
`@carbon/layout 0.0.1-alpha.12`
`@carbon/type 0.0.1-alpha.12`

Attempting to load @carbon/type into my project using SCSS.

Here is my next.config.js file, which I have used previously to load CSS into my project for the old @ibmduo type, colors, etc. I have reconfigured it to accept SCSS.

```
const withCSS = require("@zeit/next-css");
const withSass = require("@zeit/next-sass");

module.exports = withCSS(
  withSass({
    webpack(config, options) {
      config.module.rules.push({
        test: /\.(png|jpg|gif|svg|eot|ttf|woff|woff2)$/,
        use: {
          loader: "url-loader",
          options: {
            limit: 100000
          }
        }
      });
      return config;
    }
  })
);
```

When I drop `import { heading02 } from "@carbon/type";` into my _app.js file, I receive the following error...

![image](https://user-images.githubusercontent.com/15822070/50910594-be2b4c00-13f3-11e9-8ad2-9d3b4ec879b6.png)

When I follow that error, I end up here..

![image](https://user-images.githubusercontent.com/15822070/50910662-e0bd6500-13f3-11e9-8425-6a7f63d281b3.png)

That's about when I saw the wicked-crazy math and tapped out. I noticed #124 has a similar issue as what I'm having.

When I attempted to make a generic SCSS file off the root of my project and manually import the type..

```
@import "/node_modules/@carbon/type/scss/styles";
@import "/node_modules/@carbon/type/scss/reset";
@import "/node_modules/@carbon/type/scss/font-family";
@import "/node_modules/@carbon/type/scss/scale";
@import "/node_modules/@carbon/type/scss/spacing";
```

I get the following error..

![image](https://user-images.githubusercontent.com/15822070/50911003-938dc300-13f4-11e9-9027-33e5ae3d07f4.png)

**Comment by joshblack** [comment]
Gonna close this for now, let me know if this pops up again!

**Comment by sstrubberg** [comment]
Updated to `0.0.1-alpha.26` and i was able to use Styled Components. Super sweet!

This may seem like a silly question, but what is the syntax to import the type in my React app so I can use classNames?

**Comment by joshblack** [comment]
Hey @sstrubberg! If you're using `scss` and can import `.scss` files, then I believe you'll need to do the following when you including all your styles:

```
import '@carbon/type/scss/_classes.scss';
```

This should include all the type classes for you to use!

**Comment by sstrubberg** [comment]
Brought in `import "@carbon/type/scss/_classes.scss";` into my _app.js file.

Here is the error i get.

```
 ERROR  Failed to compile with 1 errors                                                               2:04:20 PM

 error  in ./node_modules/@carbon/type/scss/_classes.scss

Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/lib/loader.js):

@import '@carbon/import-once/scss/import-once';
^
      File to import not found or unreadable: @carbon/import-once/scss/import-once.
      in /Users/scottstrubberg/design-careers-site/node_modules/@carbon/type/scss/_classes.scss (line 8, column 1)
    at runLoaders (/Users/scottstrubberg/design-careers-site/node_modules/webpack/lib/NormalModule.js:286:20)
    at /Users/scottstrubberg/design-careers-site/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /Users/scottstrubberg/design-careers-site/node_modules/loader-runner/lib/LoaderRunner.js:230:18
    at context.callback (/Users/scottstrubberg/design-careers-site/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Object.asyncSassJobQueue.push [as callback] (/Users/scottstrubberg/design-careers-site/node_modules/sass-loader/lib/loader.js:55:13)
    at Object.<anonymous> (/Users/scottstrubberg/design-careers-site/node_modules/async/dist/async.js:2271:31)
    at Object.callback (/Users/scottstrubberg/design-careers-site/node_modules/async/dist/async.js:969:16)
    at options.error (/Users/scottstrubberg/design-careers-site/node_modules/node-sass/lib/index.js:294:32)

 @ ./pages/_app.js 52:0-41
 @ multi ./pages/_app.js
```
