### ISSUE TITLE
Decide on interaction colors in colors package

### ISSUE THREAD

**Issue by joshblack** [IBM/carbon-elements#238]
We're currently using some of the hover colors from the interaction palette in our tokens, would it be worthwhile for us to add support for them as variables in scss in our colors package?

cc @aagonzales @shixiedesign

**Comment by aagonzales** [comment]
We can. I think maybe hosting the whole gray and blue interactive palette would be fair.

**Comment by joshblack** [comment]
Sounds good to me! Where should I get the latest values @aagonzales?

**Comment by aagonzales** [comment]
I can't find the active colors anywhere but I think those are just the next full step up on the chart. ie active-gray-10: gray-20

**Comment by joshblack** [comment]
After chatting with @jeanservaas, we're going to defer on interaction colors until we have a better way of applying color that makes it easy to white-label.
