### ISSUE TITLE
Create migration table for color tokens

### ISSUE THREAD

**Issue by joshblack** [IBM/carbon-elements#241]
We need to create a migration table for our color tokens that outlines the following changes to tokens:

- When a token is renamed
- When a token is added
- When a token is removed

There is currently a template for this work available [on Box](https://ibm.box.com/s/2z73talqo6h219wrpc8l8mf4hscdin9h).

**Comment by aagonzales** [comment]
Yup! Sure does that's perfect. ⭐️
