### ISSUE TITLE
Create migration table for motion 

### ISSUE THREAD

**Issue by joshblack** [IBM/carbon-elements#257]
We have a variety of motion values that need to be documented for X, including:

```scss
$carbon--ease-in: cubic-bezier(0.25, 0, 1, 1); // Used primarily for removing elements from the screen.
$carbon--ease-out: cubic-bezier(
  0,
  0,
  0.25,
  1
); // Used for adding elements to the screen or changing on-screen states at a users's input.
$carbon--standard-easing: cubic-bezier(0.5, 0, 0.1, 1); // Used for the majority of animations.

// For back-ward compatibility
$bx--ease-in: $carbon--ease-in;
$bx--ease-out: $carbon--ease-out;
$bx--standard-easing: $carbon--standard-easing;

$transition--base: 250ms;
$transition--expansion: 300ms;
```

**Comment by joshblack** [comment]
Box note to use cc @shixiedesign https://ibm.box.com/s/kl4veivvh8mqixv2t5qpu5q0seqjpeq8

**Comment by shixiedesign** [comment]
@joshblack I believe I've finished updating the boxnote. Would you take a look and lemme know if it looks complete?

**Comment by joshblack** [comment]
Looks great, thanks @shixiedesign!

**Comment by shixiedesign** [comment]
Check with Josh where this info is gonna live (motion package repo?) and loop back to Clay.

**Comment by joshblack** [comment]
Most likely this is going to live in the `migrate-to-10.x.md` file in `carbon-components`!

**Comment by shixiedesign** [comment]
Updated migration table! The content in the boxnote is now ready for use. 
https://ibm.box.com/s/kl4veivvh8mqixv2t5qpu5q0seqjpeq8

| v9  | Value in v9  | 10 |  Value in v10 | 
|---|---|---|---|
| carbon--ease-in | cubic-bezier(0.25, 0, 1, 1) | carbon--ease-in | cubic-bezier(0.2, 0, 1, 0.9) |
| carbon--ease-out | cubic-bezier(0, 0, 0.25, 1) | carbon--ease-out | cubic-bezier(0, 0, 0.38, 0.9) |
| carbon--standard-easing | cubic-bezier(0.5, 0, 0.1, 1) | carbon--standard-easing | cubic-bezier(0.2, 0, 0.38, 0.9) |
| transition--base | 250ms | transition--base | 100ms |
| transition--expansion | 300ms | transition--expansion | 150ms |
