### ISSUE TITLE
Optimize entrypoint icon bundles to use icons only meant for product

### ISSUE THREAD

**Issue by joshblack** [IBM/carbon-elements#281]
We should decide on what should be included in the default entrypoint as currently it's very large. Most likely this would mean choosing a reduced set of 16x16 and 20x20 icons as these should be the sizes that are used most often in product. (cc @chrisconnors-ibm to confirm)

Another idea could be to add additional entrypoints per-size, e.g.:

```js
import { AddIcon16 } from '@carbon/icons-react/16';
```

**Comment by joshblack** [comment]
cc @chrisconnors-ibm @aagonzales is the intent for most folks to use 16x16 and 20x20 icons? Or should we ship all icon sizes by default?

**Comment by aagonzales** [comment]
I'm not sure I understand what is meant by the entrypoint but yes I think 20x20 and 16x16 are the most common icons for product.

**Comment by joshblack** [comment]
@aagonzales basically right now when people use `@carbon/icons` it'll include all 1700ish icons in sizes 16, 20, 24, 32. Just was seeing if, for most people, they would only use a subset of those so the file was smaller initially.
