### ISSUE TITLE
Create example using Create React App and @carbon/icons-react

### ISSUE THREAD

**Issue by joshblack** [IBM/carbon-elements#294]
We would love to include an example of using `@carbon/icons-react` with a project generated using `create-react-app`. Most likely what this would mean is that we use `create-react-app` to generate a project in: https://github.com/IBM/carbon-elements/tree/master/packages/icons-react/examples under the name `create-react-app`. This would include using `@carbon/icons-react` as an icon in `App.js`.

**Comment by metonym** [comment]
Could I take a stab at this?

**Comment by joshblack** [comment]
Yes please! Would be great @metonym, let me know how I can help out!
