### ISSUE TITLE
Columns not mobile-first on grid

### ISSUE THREAD

**Issue by seejamescode** [IBM/carbon-elements#30]
When elements have a size specified at their breakpoint, they work perfectly. Below is an example of items defined to be 1 column wide at the `lg` breakpoint.

![sep-26-2018 14-07-47](https://user-images.githubusercontent.com/7519029/46103178-cf7a8080-c195-11e8-9cf5-acd25e0bb759.gif)

However, I would expect each of those items to have a width of `100%` until their size is specified. Without that full width in previous breakpoints, the items have unpredictable widths. Without this, the code requires the dev to specify column classnames on every item at every breakpoint.

**Comment by joshblack** [comment]
Implemented!
