### ISSUE TITLE
[Themes] Which theme is appropriate for dark UIs?

### ISSUE THREAD

**Issue by jendowns** [IBM/carbon-elements#302]
## Detailed description

Hey all, we have a dark-themed UI so we were hoping to find a `@carbon/themes` color set that closely matched what we were trying work with. So far we've settled on `g10`, but the color application for ghost buttons is not accessible:

<img width="312" alt="screen shot 2019-01-28 at 10 32 32 am" src="https://user-images.githubusercontent.com/9057921/51850772-0bf6ee00-22e8-11e9-9230-ce036ec823de.png">

(We were hoping for more of a Blue 40 here 🤔 )

So are we just applying the wrong theme? Or are none of the themes truly optimized for a "dark" UI? (If it's latter, would you like for us to propose a theme?)

**Comment by joshblack** [comment]
cc @IBM/carbon-designers

**Comment by jendowns** [comment]
A couple notes:

* I think the usage of `$interactive-03` for both primary button colors *and* ghost button text colors should be revisited. It works for light UIs but doesn't for dark UIs.

* I've only really looked closely at buttons in this context so I don't have much insight into how the theme affects other components in a dark UI environment.

**Comment by joshblack** [comment]
@aagonzales very possible, I don't see `interactive-03` in our buttons yet upstream so that's probably it.

**Comment by jendowns** [comment]
Thanks @joshblack & @aagonzales!

> Ghost buttons and tertiary buttons should be using $interactive-03 token which is white in the dark themes.

I agree! But I think the color for Ghost Buttons (text color and icon fill) is currently coming from `$interactive-01`. I did my quick "hot pink" check (i.e., changed `$interactive-01` to `hotpink` 😆), and it affected primary button background color *and* the ghost buttons.

**Comment by aagonzales** [comment]
@jendowns changing the color of the primary buttons ($interactive-01) in dark theme will be something that has to be escalated to the brand team (ie Mike).

I also think the secondary style of the danger button has been removed from the system. There is only the filled version in V10 according the "Duo" specifications. I think this decision was made for the very reasons you brought up.

**Comment by jendowns** [comment]
@aagonzales So we have a color palette we can propose as a new theme for `@carbon/themes` and include Mike as a reviewer -- is that something you all would be interested in?

Either way, we can totally just apply our own theme here, following the patterns in `@carbon/themes`

And it sounds like the issue with `$interactive-01` applying both primary and ghost buttons needs to be a bug report?

**Comment by aagonzales** [comment]
Yeah it sounds like a bug for the ghost button issue.

**Comment by jendowns** [comment]
Closing this out because it looks like we need `g90` or `g100` if we want to use a provided theme 👍 

Also opened an issue about the ghost button color here: https://github.com/IBM/carbon-components/issues/1692
