### ISSUE TITLE
Carbon Elements Colors Preview isn't working

### ISSUE THREAD

**Issue by techtolentino** [IBM/carbon-elements#309]
## Detailed description

> Describe in detail the issue you're having.  

**When visiting the [Carbon Elements site](https://carbon-elements.netlify.com/) and clicking on the @Carbon/Colors > Preview, nothing renders on the page.**  

> Is this a feature request (new component, new icon), a bug, or a general issue?  

**bug** 🐛 

> Is this issue related to a specific component?  

**No**

> What browser are you working in?  

**Chrome - Version 71.0.3578.98 (Official Build) (64-bit)**

## Steps to reproduce the issue

1. Visit the [Carbon Elements site](https://carbon-elements.netlify.com/)
2. Under @carbon/colors click on Preview
3. See blank page

## Additional information

Console errors:

```
Failed to load resource: the server responded with a status of 404 ()   src.ca16c9c8.js:1 
Failed to load resource: the server responded with a status of 404 ()   styles.64c0d98b.css:1 
```

**Comment by joshblack** [comment]
Should be fixed!
