### ISSUE TITLE
Icons Angular need `@carbon/icon-helpers` as a dependency

### ISSUE THREAD

**Issue by zvonimirfras** [IBM/carbon-elements#315]
## Detailed description

Installing following readme gives _many_ errors along the lines of

```
ERROR in ./node_modules/@carbon/icons-angular/lib/wireless-checkout/24.js
Module not found: Error: Can't resolve '@carbon/icon-helpers' in './node_modules/@carbon/icons-angular/lib/wireless-checkout'
```

until `@carbon/icon-helpers` are installed. That should be documented (possibly added as a peerDependency) or helpers should be a dependency.

**Comment by joshblack** [comment]
Hi @zvonimirfras! 👋  I believe it's already listed as a dependency: https://github.com/IBM/carbon-elements/blob/master/packages/icons-angular/package.json#L32

Are you using the latest with `npm i @carbon/icons-angular@alpha`?

**Comment by joshblack** [comment]
Going to close this as I believe it's resolved. Feel free to re-open/comment if not!
