### ISSUE TITLE
[Type] Document how new type styles replace old typescale names

### ISSUE THREAD

**Issue by jendowns** [IBM/carbon-elements#321]
**Is your feature request related to a problem? Please describe.**
We'd like to have a reference that shows us, for example, what to replace old type scales like `@include typescale('zeta');` with

**Describe the solution you'd like**
A type that shows a 1:1 relationship between old typescale and new type styles/variables.

**Comment by joshblack** [comment]
Hi @jendowns! This is initially documented here: https://ibm.box.com/s/b87gaanauy23o7ko321cohoarq07u0rj will add a markdown file or something to help out in the relevant projects 👍

**Comment by joshblack** [comment]
This should also totally be part of our upgrade tool now that I'm thinking about it 🤔

**Comment by jendowns** [comment]
@joshblack The upgrade tool won't suit our needs just yet since we are going through each of our existing components, stripping out that private fork, and replacing them with Carbon X equivalents (usually involves a lot of deletion). 

Usually when we do this, the Carbon X equivalent isn't quite ready... for example, the `Accordion` X version uses `typescale('zeta')` still in `carbon-components`, so in our library when we import that component, we have to override that with `type-style($name: body-short-01)`. But we have to know that `typescale('zeta')` = `type-style($name: body-short-01)`. The upgrade tool wouldn't help us here since the upgrade is supposed to happen in `carbon-components`

A table like this would be really helpful --
```
| Deprecated  | Replacement   |
| ----------- | ------------- |
| zeta        | body-short-01 |
```

**Comment by jendowns** [comment]
Just now looking at that box note... a table definitely would have come in handy, as I already guessed incorrectly that the Accordion's `zeta` = `body-short-01` (it's actually `body-long-01`). 🙃 Oops

**Comment by joshblack** [comment]
Added in: https://github.com/IBM/carbon-elements/blob/master/docs/migration/10.x-type.md
