### ISSUE TITLE
Contribution: Home

### ISSUE THREAD

**Issue by Ryan-Reed** [IBM/carbon-elements#324]
#### 4. Box Link
https://ibm.box.com/s/udr4lxh57e6zg58t7o4b9a01kn5eomeo

#### 5. Screen Shot

Please add the following screen shots to this issue:

1.  Close-up screen shot of the icon with the pixel grid turned on

![image](https://user-images.githubusercontent.com/46900476/51488956-ec564780-1d74-11e9-9fde-9919f046521a.png)

2.  Screen shot of the icon in context with your use case.

![image](https://user-images.githubusercontent.com/46900476/51489743-32aca600-1d77-11e9-9ef9-c97ec5d57d6c.png)

**Comment by asudoh** [comment]
Moved to `carbon-elements` repo, which host latest set of icons. Feel free to let us know if a new icon in our legacy repo is needed. Thanks!

**Comment by aharbis** [comment]
@asudoh Can you help clarify the steps to get this landed? The main readme for this repo shows this as an experimental package, so just trying to understand the path to get the Home icon added to Carbon.

**Comment by joshblack** [comment]
I believe we have a home icon in the latest batch of IBM Design Language icons, specifically: https://carbon-elements.netlify.com/icons/examples/preview/#32%2Fhome! 😄

**Comment by joshblack** [comment]
Going to close this for now as I believe the Home icon is already established in the new IDL icons. Be on the lookout for a stable release for this project alongside Carbon v10!
