### ISSUE TITLE
Motion package using wrong css property 

### ISSUE THREAD

**Issue by tw15egan** [IBM/carbon-elements#325]
The motion package is currently setting a bezier-curve on the `transition-property` CSS property. It should instead be applying this value to the `transition-timing-function` property. This mixing could/should be expanded to include durations in the mixin

Current:
![screen shot 2019-02-07 at 11 30 20 am](https://user-images.githubusercontent.com/11928039/52430510-dd3cfc80-2acb-11e9-820c-dfa01bbdc9a5.png)

Proposed:
![screen shot 2019-02-07 at 11 33 12 am](https://user-images.githubusercontent.com/11928039/52430650-33aa3b00-2acc-11e9-9a60-8a3620635934.png)

**Comment by joshblack** [comment]
Closed by #326! Thanks @tw15egan 😄 Will cut a release soon! Hopefully today/tomorrow
