### ISSUE TITLE
@carbon/type:weights

### ISSUE THREAD

**Issue by sstrubberg** [IBM/carbon-elements#335]
## Title line template: [@carbon/type]: weights

![image](https://user-images.githubusercontent.com/15822070/52485895-7da02900-2b7f-11e9-8e69-f65acc5a3fc8.png)

`display-01` should have a weight of 300, as shown in the computed section. However, the browser rendered font Plex Extra Light as opposed to Plex Light. I get the with pretty much every class i use.

Here is a [link](https://github.ibm.com/Design/design-careers-site/tree/carbon-migration) to my branch where I'm messing with this.

NPM packages:
```
@carbon/colors": "0.0.1-alpha.31
@carbon/icons-react": "0.0.1-alpha.31
@carbon/layout": "0.0.1-alpha.31
@carbon/type": "0.0.1-alpha.31
```

SCSS file being imported:
```
@import "@carbon/type/scss/type.scss";
@import "@carbon/type/scss/_classes.scss";

@include type-reset();
@include type-classes();
```

**Comment by joshblack** [comment]
Hey @sstrubberg! 👋 Do you notice the same issue here: https://carbon-elements.netlify.com/type/examples/preview/ ?

**Comment by sstrubberg** [comment]
![image](https://user-images.githubusercontent.com/15822070/52504806-2f0a8300-2baf-11e9-8028-b4642036d7a2.png)

No, that's what confuses me. I have what I think is an identical setup as your preview site, but things aren't rendering right.

However, on the preview site, I noticed that when I manually set the weight to 200, it's rendering Plex Light and not Extra Light.

**Comment by joshblack** [comment]
@sstrubberg could you try disabling the system font to see if it's an issue with the font-face definition or if it's related to a local font problem? 

I've removed it temporarily by:

- Opening font book and finding Plex
- Clicking "open in finder"
- Going up one level and moving the managed folder to my desktop
- Reloading the site to verify it grabs fonts from network
- WHen done, moving managed folder back into fonts directory

**Comment by sstrubberg** [comment]
Ok, did all the steps. Now it's just loading Helvetica Neue. I'm guessing I'm not actually loading Plex correctly on my site then...?

**Comment by sstrubberg** [comment]
Cancel that, i just quick the browser and reloaded it. Back to the original issue.

**Comment by sstrubberg** [comment]
Ugh.. thank you for humoring me with this conversation. Turns out I failed to enter the following line in my SCSS file..

`
@import "@carbon/type/scss/font-face/sans";
`

It's behaving just like the preview site now :)

**Comment by joshblack** [comment]
Woohoo! Sounds good @sstrubberg! Glad it's working now 🎉 

Just a heads up, I recently added some docs for `@carbon/type` in: https://github.com/IBM/carbon-elements/tree/master/packages/type#usage the big change for you might be that you will have to call the mixins manually like:

```scss
@import '@carbon/type/scss/type';
@import '@carbon/type/scss/font-face/mono';
@import '@carbon/type/scss/font-face/sans';

@include carbon--type-reset();
@include carbon--font-face-mono();
@include carbon--font-face-sans();
```

Just wanted to give you a heads up before our next release!
