### ISSUE TITLE
IE11: Remove use of `unset` in CSS

### ISSUE THREAD

**Issue by mattrosno** [IBM/carbon-elements#336]
https://caniuse.com/#feat=css-unset-value

`unset` is not supported by IE11, and it's being used in a handful of places. Those should be replaced with `inherit`, `initial`, or the property's default value where appropriate.

See screenshot in https://github.com/IBM/carbon-components/issues/1761 for some instances.

**Comment by joshblack** [comment]
Thanks @mattrosno! Fixed in: https://github.com/IBM/carbon-elements/commit/c0ca2b1ec6677b4bb3858ef6242efaa20aadb6df and added a stylelint rule so it's not used again 👍
