### ISSUE TITLE
Update @carbon/icons-angular to not have a default entrypoint

### ISSUE THREAD

**Issue by joshblack** [IBM/carbon-elements#350]
Due to size concerns of our icon library, we're going to initially default to requiring the full path for an icon component. For example:

```js
// Not preferred, bundle size problems
import { SomeIcon } from '@carbon/icons-angular'

// Preferred
import SomeIcon from '@carbon/icons-angular/es/some-icon/size';
```

This issue is for implementing this pattern in `@carbon/icons-angular`.

**Comment by joshblack** [comment]
cc @cal-smith, do you think you'll have some time over the next week or two to help out with this? Locked the package as private in the meantime so we don't publish over existing packages 👍

**Comment by cal-smith** [comment]
Yep 👍 I'll make some time to take a look

I can't seem to assign myself to the issue, but my name should be on this one
