### ISSUE TITLE
Add focusable="false" attribute to SVG components

### ISSUE THREAD

**Issue by joshblack** [IBM/carbon-elements#36]
As noted in https://github.com/IBM/carbon-components-react/issues/1392, we should probably add `focusable="false"` to our Icon components so that we can handle the identified IE11 issue.

**Comment by asudoh** [comment]
From https://github.com/IBM/carbon-components-react/issues/1392#issuecomment-426827634 - The thing we need here is ensuring an interface in the new icon React components to allow consumer to set that attribute.

**Comment by joshblack** [comment]
For sure 👍 will add to prop-type definition of `Icon` in: https://github.com/IBM/carbon-elements/blob/master/packages/icons-react/src/tools.js#L10

**Comment by joshblack** [comment]
Implemented!
