### ISSUE TITLE
Create /16/warning--filled.svg with black [!] 

### ISSUE THREAD

**Issue by chrisconnors-ibm** [IBM/carbon-elements#360]
Relating to https://github.com/carbon-design-system/carbon-website/issues/797

**Describe the solution you'd like**
Create a new `/16/warning--filled.svg` where the bg can be styled with a color and the `!` will be `black` rather than knocked out the the container BG

**Describe alternatives you've considered**

**Additional context**

**Comment by shixiedesign** [comment]
Created icon: 
SVG file: https://ibm.box.com/s/zn7ifvqg3907d977325z14y0ffmwb1v1
![warning--yellow](https://user-images.githubusercontent.com/15144993/53505166-f3a9f880-3a78-11e9-9bae-45339f142953.png)

**Comment by chrisconnors-ibm** [comment]
it's not currently practice to encode color values other than black in our icons. my suspicion is that a more consistent method with be `black` fill with a `white` exclamation point that can be independently styled in code - @joshblack would that work?

**Comment by chrisconnors-ibm** [comment]
There's also some irregularities wrt to the sizes of the exclamation mark paths:
![image](https://user-images.githubusercontent.com/35537391/53506446-fbbb6580-3a83-11e9-9341-365e4360503f.png)

We'll need bespoke 16, 20, and 24 px sizes once we settle on the execution.

**Comment by joshblack** [comment]
Just for context, the build step strips out most of the colors under the assumption that the icons will need to be styled with whatever color a team using the icon might need. In the case of this icon, we might need to be able to style both the fill of the icon (yellow bg) and the fill (or whatever property) of the punch-out to be black. If the path for the icon is distinct, then we should be able to style it directly in CSS by targeting the specific path.

**Comment by shixiedesign** [comment]
Here's the SVG. Does that look workable for you? @joshblack 
```
<?xml version="1.0" encoding="UTF-8"?>
<svg version="1.1" viewBox="0 0 32 32" xmlns="http://www.w3.org/2000/svg">
<title>warning--yellow</title>
<desc>Created with Sketch.</desc>
<g fill="none" fill-rule="evenodd">
<g transform="translate(2 2)" fill-rule="nonzero">
<path d="m14 8.8818e-16c-7.732-1.3323e-15 -14 6.268-14 14s6.268 14 14 14 14-6.268 14-14c0-3.713-1.475-7.274-4.1005-9.8995-2.6255-2.6255-6.1865-4.1005-9.8995-4.1005z" fill="#FDD13A"/>
<polygon points="12.87 6 15.12 6 15.12 17 12.87 17" fill="#000"/>
<path d="m14 23c-0.60669 0-1.1536-0.36546-1.3858-0.92597-0.23217-0.56051-0.10384-1.2057 0.32516-1.6347s1.0742-0.55733 1.6347-0.32516c0.56051 0.23217 0.92597 0.77913 0.92597 1.3858 0 0.82843-0.67157 1.5-1.5 1.5z" fill="#000"/>
</g>
</g>
</svg>
```

**Comment by shixiedesign** [comment]
@chrisconnors-ibm omg...i will re-do one with illustrator.

**Comment by chrisconnors-ibm** [comment]
Don't make the bg `yellow` - make it `black` with the exclamation mark `white`

**Comment by shixiedesign** [comment]
I'm making the 32x32 one for now.  We need 20x20 for Notification.

**Comment by shixiedesign** [comment]
SVG in PR
![warning--yellow-01](https://user-images.githubusercontent.com/15144993/53510532-d890b600-3a83-11e9-93fe-8a40ef21de9c.png)

**Comment by chrisconnors-ibm** [comment]
Have a look at this file with all 4 artboards: https://ibm.box.com/s/njwi9j36365myvn8rpqjjxdt1k2hbnl8

**Comment by shixiedesign** [comment]
that looks like a different icon than the SVG we have in the repo...it looks nicer. Where did the `warning--filled` icon in our SVG repo come from then?

**Comment by chrisconnors-ibm** [comment]
that is warning.svg.

**Comment by chrisconnors-ibm** [comment]
this solid block style is why our 20 and 16 look so rough. The taper on the Plex Sans [!] hides some sins at the smaller resolutions:
![image](https://user-images.githubusercontent.com/35537391/53526461-4653d680-3ab2-11e9-8654-e8ff7e39f293.png)
