### ISSUE TITLE
Contribution: Undo icon

### ISSUE THREAD

**Issue by m-battelli** [IBM/carbon-elements#362]
**Is your feature request related to a problem? Please describe.**
The usage of "reset" icon seems a little bit inappropriate for a text toolbar.

**Describe the solution you'd like**
I have designed this icon for a new component, Text toolbar #361 
It can be used to erase the text you have just typed.

All files here: https://ibm.box.com/s/c0z2ow5uiexi8zu3s56uhptdwcuq99yp

Screenshot details:
<img alt="screen shot 2019-02-12 at 10 53 26" width="1184" src="https://user-images.githubusercontent.com/47557215/52626894-75642880-2eb4-11e9-81dd-1254d0b9fa64.png">

<img alt="screen shot 2019-02-12 at 11 09 57" width="409" src="https://user-images.githubusercontent.com/47557215/52628003-e99fcb80-2eb6-11e9-8fd4-c16f1e45a666.png">

**Comment by joshblack** [comment]
Hi @m-battelli! 👋 We might have an icon like this already here: https://carbon-elements.netlify.com/icons/examples/preview/#32%2Freset is this matching what you're looking for?

cc @chrisconnors-ibm

**Comment by chrisconnors-ibm** [comment]
I am fine with a specific pair for undo/redo, and am working with @m-battelli to make adjustments to the source so that they are trued up on the pixel grid, placed in the right directories, etc.

**Comment by m-battelli** [comment]
Thank you @chrisconnors-ibm @joshblack

**Comment by chrisconnors-ibm** [comment]
here's what the 32px art should look like in Illustrator in `Pixel Preview` mode:
<img width="817" alt="screen shot 2019-02-21 at 10 46 21 am" src="https://user-images.githubusercontent.com/35537391/53181795-40e42100-35c6-11e9-963b-e18332ca7a62.png">
