### ISSUE TITLE
Contribution: Redo icon

### ISSUE THREAD

**Issue by m-battelli** [IBM/carbon-elements#363]
**Is your feature request related to a problem? Please describe.**
The usage of "restart" icon seems a little bit inappropriate for a text toolbar.

**Describe the solution you'd like**
I have designed this icon for a new component, Text toolbar #361
It can be used to erase the text you have just typed.

All files here: https://ibm.box.com/s/z6ebqcilwvi40dahzyihmhcpvwing2rl

Screenshot details:
<img alt="screen shot 2019-02-12 at 10 56 53" width="802" src="https://user-images.githubusercontent.com/47557215/52627092-f0c5da00-2eb4-11e9-9ecf-e200b6d54179.png">

<img alt="screen shot 2019-02-12 at 11 09 57" width="409" src="https://user-images.githubusercontent.com/47557215/52628405-e22cf200-2eb7-11e9-9799-790dc0ceb3a3.png">

**Comment by joshblack** [comment]
Hi @m-battelli! 👋 Thanks so much for taking the time to make this issue 😄 

We do currently have an icon that could satisfy this use case here: https://carbon-elements.netlify.com/icons/examples/preview/#32%2Frestart, is that matching what you're looking for?

cc @chrisconnors-ibm

**Comment by chrisconnors-ibm** [comment]
closed by #373
