### ISSUE TITLE
Contribution: Selected item icon

### ISSUE THREAD

**Issue by m-battelli** [IBM/carbon-elements#364]
**Is your feature request related to a problem? Please describe.**
The usage of checkbox or checkmark icon seems not completely compatible with differentl types of lists.
Examples:
<img width="135" alt="screen shot 2019-02-20 at 12 04 10" src="https://user-images.githubusercontent.com/47557215/53087522-b0470b80-3507-11e9-8dfc-0e648720b775.png">
<img width="201" alt="screen shot 2019-02-20 at 12 04 19" src="https://user-images.githubusercontent.com/47557215/53087529-b2a96580-3507-11e9-80bd-8ea9a91fdf32.png">

**Describe the solution you'd like**
I have designed this icon for a new component, Text toolbar #361 
It can be used for the selection in the list (examples: font style, font color, and font size).

All files here: https://ibm.box.com/s/ze88hjcwaoil5pi26d0llf2zmpy9jf5r

Screenshot details:
<img alt="screen shot 2019-02-12 at 10 47 57" width="1238" src="https://user-images.githubusercontent.com/47557215/52628591-48b21000-2eb8-11e9-97ea-e68d73bb497d.png">

<img alt="screen shot 2019-02-12 at 11 20 28" width="1429" src="https://user-images.githubusercontent.com/47557215/52628604-510a4b00-2eb8-11e9-9075-4fece12d1b6e.png">

**Comment by joshblack** [comment]
cc @chrisconnors-ibm

**Comment by chrisconnors-ibm** [comment]
this one was tricky - let's have @conradennis take a look and work with you to get it trued up on the pixel grid. He'll be back Feb 26.
