### ISSUE TITLE
Add new color tokens

### ISSUE THREAD

**Issue by aagonzales** [IBM/carbon-elements#366]
Two more color tokens to be added: 

Token | White Theme | G10 Theme | G100 Theme | G90 Theme | Usage
-- | -- | -- | -- | -- | --
$interactive-04 | Blue 60 / `#0062ff` | Blue 60 / `#0062ff` | Blue 50 / `#408bfc` | Blue 50 / `#408bfc` | Selected nav indicator; Active elements
$link-01 | Blue 60 / `#0062ff` | Blue 60 / `#0062ff` | Blue 40 / `#6ea6ff` | Blue 40 / `#6ea6ff` | Primary links

**Comment by aagonzales** [comment]
Note: `$interactive-01` is now only for buttons, all other uses that we're assigned to `$interactive-01` now use `-04`

**Comment by joshblack** [comment]
Nice @aagonzales! Did anyone on design want to try and add them, or should we add it to the dev sprint? No problem either way 😄 happy to help if anyone wants to learn how to contribute them, as well 👍

**Comment by aagonzales** [comment]
I think @shixiedesign knows how to do it right? So maybe she can show me how.
