### ISSUE TITLE
Some icons showing up as completely black on Carbon site

### ISSUE THREAD

**Issue by conradennis** [IBM/carbon-elements#367]
## "Recording--Filled" and "Recording--Alt" icons are showing up as black circles on the Carbon site

SVGs on the design end seem to be fine, @joshblack mentioned it could be the transparent rectangle causing the issue.

<img width="281" alt="screen_shot_2019-02-20_at_1 44 43_pm" src="https://user-images.githubusercontent.com/16782944/53120024-e04dd900-351e-11e9-9da5-297241fad061.png">
<img width="242" alt="screen_shot_2019-02-20_at_1 44 47_pm" src="https://user-images.githubusercontent.com/16782944/53120025-e04dd900-351e-11e9-8c0d-0ff442b8e0d9.png">
<img width="686" alt="screen_shot_2019-02-20_at_1 47 13_pm" src="https://user-images.githubusercontent.com/16782944/53120026-e04dd900-351e-11e9-8d72-33f09f44c7e7.png">

**Comment by joshblack** [comment]
Looking into this more, seems like the inner `path` is having its `fill` stripped by the build process. Will need to investigate what's the best way to resolve this 🤔

**Comment by joshblack** [comment]
cc @chrisconnors-ibm I think this is the same two-tone issue, do we want to add this to the current sprint?

**Comment by chrisconnors-ibm** [comment]
I can fix these in pr #375 if you want

**Comment by joshblack** [comment]
Let's do ittt @chrisconnors-ibm

**Comment by joshblack** [comment]
Closed in #375
