### ISSUE TITLE
non-eyeglass sass imports that avoid the node-sass `importer` slowdown

### ISSUE THREAD

**Issue by scottnath** [IBM/carbon-elements#376]
## Problem overview

When using sass `import` statements to import carbon Sass files in an _environment which cannot use eyeglass_, we cannot import `@carbon/type` due to it's reliance on `@carbon/layout/scss/breakpoint`. 

We have also ran into an issue where [the node-sass importer function is slowing down sass processing time](https://github.com/IBM/carbon-elements/issues/372).

### We use carbon via npm, we export our system as an npm module

We create sass files using Carbon Sass files, importing them via Sass `import` statements. In turn, we create an npm module, which exports our Sass files, which are then used by applications which have us as a dependency.

#### sass `import` example:

```
@import '~carbon-components/scss/components/button/button';
@import './mixins';
(rest of sass file)
```

#### node-sass `importer` function

We then use an `importer` function within node-sass that converts the tilde to the correct path to node modules:

```
        importer: orig => {
          let url = orig;
          const parentContainer = path.dirname(
            path.join(__dirname, '../../../')
          );
          url =
            path.basename(parentContainer) === 'node_modules'
              ? path.join(parentContainer, url.substr(1))
              : path.join(process.cwd(), 'node_modules', url.substr(1));

          return { file: url };
        },
```

The above `importer` function will do one of two things:
1. find the `node_modules` directory when doing local development on our repo
1. find the `node_modules` directory for an app which has us as a dependency

## About our users

Like any open source project, varied in their technology options. A specific one that cannot use `eyeglass` is using Angular CLI. They have limited configuration options and can only adjust the `importer` function, but cannot add `eyeglass`.

## Acceptance criteria

- [ ] can use `@carbon/type` without installing `eyeglass`
- [ ] technical solutions/experiments to avoid the node-sass `importer` slowdown

thank you!

**Comment by joshblack** [comment]
Hey @scottnath! We do offer an entrypoint with everything inlined with `@carbon/elements`, would the preference be for each package to have an option like that?

**Comment by joshblack** [comment]
As an aside, can they control options passed to `node-sass`? If so, adding `node_modules` to `includePaths` is another option here.

**Comment by repjarms** [comment]
I believe this same issue applies to situations where `eyeglass` would need to be integrated with the build system. For example, if a user is using `create-react-app` and is not ejecting, they do not have control over their `webpack` configuration without ejecting.

This is a situation we are running into now, as we are trying to make a template that we can use for applications running Watson apis with carbon packages. We are able to import the top level carbon scss packages using tilde imports or by prefixing the import with `node_modules`, but nested imports within the packages are not imported correctly.

**Comment by repjarms** [comment]
In the specific case that I mentioned above, this issue is avoided by importing the bundled scss file in `@carbon/elements` instead of the packages individually. However, for importing an scss file individually, i.e. `@import node_modules/@carbon/grid/scss/grid`, the above issue applies.
