### ISSUE TITLE
add editorial set and edit quotation section

### ISSUE THREAD

**Issue by eraymond25** [IBM/carbon-elements#39]
**Is your feature request related to a problem? Please describe.**
Digital Design would like to pull from your open source type sets in future

**Describe the solution you'd like**
We would like you to add editorial set to your repo and change current quotation-01 to quotation-02 so that we can add a smaller quotation-01 to the set. See quotation sizes here: https://www.ibm.com/standards/web/elements/type-usage.html

**Describe alternatives you've considered**
We've been testing quote sizes with teams like Watson and the current quotation is too large for certain, less punchy scenarios

**Additional context**
Wonil may have more light on the quotation issue

**Comment by joshblack** [comment]
Closing in favor of #104
