### ISSUE TITLE
Define themes in a Sass map for better theme customization

### ISSUE THREAD

**Issue by mattrosno** [IBM/carbon-elements#395]
**Non-white default theme in carbon-components**

Right now, each theme has their own mixin (e.g. `carbon--theme-white`) that you can call to initialize global Sass variables. Looking at how carbon-components is including the `carbon--theme-white` mixin, how would one modify that and choose a different theme through global Sass variables?

**Inline theming**

What if we want to create an inline theme that redefines theme variables then includes components using those new theme variables? That's not possible when using carbon-elements given how the `!default` keyword is used.

**Proposal**

Move theme values to a map of themes, which map theme tokens to color values.

Provide two mixins. The first takes in a theme name and defines a Sass variable for each token using `!default` and `!global` keywords. This mixin can be used to set the default theme.

The second mixin also takes in a theme name, but this time, the Sass variables have the `!global` keyword but not `!default`, so you can redefine colors during inline theming.

**Background**

This issue originated from the RFC to better support theming and inline (zoned) theming where one theme can live inside another theme. https://github.com/IBM/carbon-components/pull/1872

**Comment by joshblack** [comment]
cc @aagonzales for the name of our "themes" are we sticking with white, g10, g90, g100?

**Comment by aagonzales** [comment]
We'll have to talk to Mike and Sadek about the theme names. With a "theme" being all tokens that can be customized (like spacing, type, etc) and not just color.
