### ISSUE TITLE
Font Performance with font-display

### ISSUE THREAD

**Issue by harshzalavadiya** [IBM/carbon-elements#476]
## Detailed description
As CarbonDesignSystem uses `IBM Plex` font. for normal network it takes time to load any webfont and by the time webfont are not loaded text will be blank that is not good user experiance.

`font-display` can be implemented while defining `@font-face` so it will display fallback fonts by the time fonts are being loaded.

## Additional information

- https://developers.google.com/web/updates/2016/02/font-display
- Lighthouse suggestion `Ensure text remains visible during webfont load: Leverage the font-display CSS feature to ensure text is user-visible while webfonts are loading.`

**Comment by asudoh** [comment]
Talked to @vpicone - Found that we currently don't support `$font-path` in `v10` either - So our suggestion would be supporting control over font path in addition to `font-display`.
