### ISSUE TITLE
Document process to update icon metadata

### ISSUE THREAD

**Issue by joshblack** [IBM/carbon-elements#489]
We should document how someone can add metadata to our icon library in a markdown file in `docs/guides/updating-icon-metadata.md`. This content can then be mirrored/transferred to the site as-needed, but could be linked to in the meantime.

This issue is to create the initial guidance for updating icon metadata for any user of carbon.

**Comment by joshblack** [comment]
cc @shixiedesign

**Comment by shixiedesign** [comment]
@joshblack trying to work on this issue but can't find the wiki for this repo. Is there one? Or should I add it to the `carbon-design-system/carbon-website` repo?

**Comment by joshblack** [comment]
@shixiedesign could you add this info to: https://github.com/IBM/carbon-elements/blob/master/docs/icons.md ?

**Comment by shixiedesign** [comment]
My bad I didn't read the issue description carefully!
