### ISSUE TITLE
Carbon X: finalize color tokens

### ISSUE THREAD

**Issue by aagonzales** [IBM/carbon-elements#53]
Duo uses color different than original Carbon color themes, we need to re-evaluate color usages and roles and add any additional color tokens.

- [x] Audit color usage in Duo components
- [x] Identify outliers and if its worthy of new token
- [x] Determine final token set
- [x] Determine final token names. Are we keeping brand?
- [x] Finalized assigned values for white theme
- [x] Write migration guidelines

**Comment by aagonzales** [comment]
## Steps:

1. Audited existing color application 
   - https://ibm.box.com/s/q52kj1mluw3ofpj83ipllqn9zsa5v3cm
2. Categorized colors by value 
   - https://ibm.box.com/s/bohbpwhqfsy1wczklphva2fyfwttw1g9
3. Grouped usage within each value
   - https://ibm.box.com/s/914o0p79ojipsw3m17xswummzvhiendi
4. Identified and resolved outliers _(red text = outliers, green text=outlier resolved)_
5. Assigned usage grouping to existing tokens or created new tokens to fit usage
   - https://ibm.box.com/s/gsn9ig73ajzep4bdtaht4mcipqwtw3lp
6. Final Tokens
   - https://ibm.box.com/s/8kouiwn37f8ijx2ql58t6hko1t8m8574

**Comment by aagonzales** [comment]
## Core Color Tokens

Token | White Theme Value | Usage
-- | -- | --
$brand-01 <br /> $interactive-01 | Blue 60 | interaction colors <br /> buttons <br /> selected elements <br /> feature elements <br /> highlight hover for ui colors <br /> accent?? icons
$brand-02 | Deprecate ?? | ??
$brand-03 <br /> $interactive-02 | Blue 60 | Loading
$ui-01 | Gray 10 / #f3f3f3 | primary container background <br /> secondary page background
$ui-02 | White | Default page background <br /> secondary container background
$ui-03 | Gray 30 | Subtle border
$ui-04 | Gray 50 | 3:1 AA element contrast <br /> medium contrast border
$ui-05 | Gray 100 | 4.5:1 AA  element contrast <br /> Emphasis border <br /> Emphasis elements
$text-01 | Gray 100 | Primary text color <br /> Text hover color for text-02 (Gray 70) <br /> Labels as headers
$text-02 | Gray 70 | Label <br /> Secondary text
$text-03 | Gray 50 | Hint text <br /> placeholder text
$icon-01 | Gray 100 | primary icons
$icon-02 | Gray 70 | secondary icon color <br /> decorative icons
$field-01 | Gray 10 | primary input field color <br /> fields on White background
$field-02 | White | Secondary input field color <br /> fields on Gray 10 backgrounds
$inverse-01 | White | Inverse text inverse icon
$inverse-02 | Gray 80 | High contrast backgrounds <br /> High contrast elements
$support-01 | Red 60 | Error <br /> Danger
$support-02 | Green 60 | Success
$support-03 | Yellow | Warning
$support-04 | Blue 70 | Informational
$overlay-01 | White @ 60% | Light background overlay
$overlay-02 | Gray 100 @ 70% | Dark background overlay

## Interaction State Tokens

Token | White Theme Value | Usage
-- | -- | --
$focus | Blue 60 | Focus border <br /> Focus underline
$hover-primary | Blue 60 Hover | Hover color for brand-01
$active-primary | Blue 80 | Active color for brand-01
$hover-primary-text | Blue 70 | Text + icon hover color for brand-01
$hover-secondary | Gray 100 hover | Hover for ui-05
$active-secondary | Gray 80 | Active-background for ui-05
$hover-ui | Gray 10 Hover #e5e5e5e | hover white elements <br /> hover Gray elements <br /> hover transparent elements
$active-ui | Gray 30 | Active background color for ui-01
$hover-danger | Red 60 Hover / #ba1b23 | Support-01 hover
$active-danger | Red 80 | Active color for support-01
$hover-row | TBD | Row hover
$visted-link | Purple 60 | Visited state for link
$disabled-01 | Gray 10 | disabled fields background <br /> disabled backgrounds <br />disabled border
$disabled-02 | Gray 30 | disabled elements on $disabled-01 (Gray 10) <br /> disabled label on $disabled-01 (Gray 10) <br /> disabled text on $disabled-01 (Gray 10) <br /> disabled icons on $disabled-01 (Gray 10) <br /> disabled border <br /> disabled background
$disabled-03 | Gray 50 | disabled text on $disabled-02 (Gray 30) <br /> disabled icon on $disabled-02 (Gray 30)

**Comment by eraymond25** [comment]
so with this are we going to have 5 different default IBM themes?

**Comment by eraymond25** [comment]
I guess I'm just confused because you have $field-02 for G10 background, but nothing else is optimized for that -- ex. $ui-04, $text-03

wouldn't that just be calling the G10 theme (or subtheme, whatever we decide to call it)

**Comment by aagonzales** [comment]
- `$ui-04`/ Gray 50 passes at 3:1 on both gray 10 (3.03:1) and white (3.36:1)
- `$text-03` is hint/placeholder text and we're still in a debate wether it needs to pass accessibility for not. Its current value is Gray 50 which doesn't pass even on white. We'd have to bump the value up to Gray 60 to work on white and it passes on Gray 10 (5.02:1) as well (4.53:1)

**Comment by eraymond25** [comment]
okay, that's good to hear, does it pass for the gray 100, 90 and 80 situation though?

Also, do we have a concrete scenario of when do you call the G10 theme versus when do you use $field-02 etc.

**Comment by aagonzales** [comment]
> okay, that's good to hear, does it pass for the gray 100, 90 and 80 situation though?

- We'd haven't evaluated those themes yet but if that the rule so if the color application in those themes aren't meeting the correct criteria for those token then we'll adjust the value not the token. 
- I can see Gray 80 have contrast issue which might be a good reason to rule it out as a theme.

> Also, do we have a concrete scenario of when do you call the G10 theme versus when do you use $field-02 etc.

- You'd target full pages for themes. I believe we're not advising people to target "zones" anymore within a page. Field-02 is in there for those moments where you'll need that other background like modal or form etc.

**Comment by joshblack** [comment]
Unrelated, but would it be possible for us to create a table of rules for when colors can be used in foreground/background? Would love to automate the contrast checks so you all don't have to do it manually!

**Comment by eraymond25** [comment]
> You'd target full pages for themes. I believe we're not advising people to target "zones" anymore 
 within a page. Field-02 is in there for those moments where you'll need that other background like modal or form etc.

Is it possible though to still target zones, especially for marketing page -- many times there are "bands" of color (we're narrowing down this practice and refining it but the band practice is still going to be used)

**Comment by aagonzales** [comment]
@tw15egan is the concept of targeting zones still possible? ^^ Is that something that a team would have to figure out themselves?

**Comment by aagonzales** [comment]
need to look into potentially changing ui-03 to Gray 20 instead of Gray 30. It works better with data table.

**Comment by joshblack** [comment]
Just let me know @aagonzales! Will update in code 😄

**Comment by aagonzales** [comment]
## New changes to color tokens
_Changes have been added to the above table as well_
Changing to make components work more closely to original Duo specs.

- Change value of `$ui-03` to `Gray 20` (originally was Gray 30)
- Add new token `$selected-ui` to interaction token set. Value for the Duo white them is`$selected-ui: Gray 20`

cc: @joshblack

**Comment by aagonzales** [comment]
**Sprint 25**: need migration docs from v9 to v10 - @aagonzales

**Comment by aagonzales** [comment]
Defined Production (Legacy) Theme values for V10 Tokens here: https://ibm.box.com/s/ohag7bv9m4s8llbevsrd4hm8druq8poz

**Comment by shixiedesign** [comment]
# Updated Color Tokens

### V10 Color tokens 

Token | White Theme | G10 Theme | G100 Theme | G90 Theme | Usage
-- | -- | -- | -- | -- | --
$interactive-01 | Blue 60 / #0062ff | same as White | same as G90 | Blue 60 / #0062ff | interaction colorsbuttonsselected elementsfeature elementshighlight hover for ui colorsaccent?? icons
$interactive-02 | G100 / #171717 | same as wWhite | same as G90 | G60 / #6F6F6F | Secondary button
$interactive-03 | Blue 60 / #0062ff | same as White | same as G90 | White / #FFFFFF | Tertiary button
$ui-background | White / #FFFFFF | G10 / #F3F3F3 | G100 / #171717 | G90 / #282828 | Default page background
$ui-01 | Gray 10 / #F3F3F3 | White / #FFFFFF | G90 / #282828 | G80 / #3D3D3D | primary container backgroundssecondary page background
$ui-02 | White / #FFFFFF | G10 / #F3F3F3 | G80 / #3D3D3D | G70 / #565656 | secondary container background (eg. form)
$ui-03 | Gray 20 / #dcdcdc | same as White | G80 / #3D3D3D | G70 / #565656 | Subtle border
$ui-04 | Gray 50 / #8c8c8c | same as White | G60 / #6F6F6F | G50 / #8c8c8c | 3:1 AA element contrast medium contrast border
$ui-05 | Gray 100 / #171717 | same as White | same as G90 | G10 / #f3f3f3 | 4.5:1 AA  element contrast Emphasis border Emphasis elements
$text-01 | Gray 100 / #171717 | same as white | same as G90 | G10 / #f3f3f3 | Primary text colorText hover color for text-02 (Gray 70)Labels as headers
$text-02 | Gray 70 / #565656 | same as white | same as G90 | G30 / #BEBEBE | LabelSecondary text
$text-03 | Gray 50 / #8c8c8c | same as white | G60 / #6F6F6F | G50 / #8C8C8C | Hint textplaceholder text
$text-04 | White / #FFFFFF | White / #FFFFFF | White / #FFFFFF | White / #FFFFFF | Primary, secondary, and danger button text
$icon-01 | Gray 100 / #171717 | same as white | same as G90 | G10 / #f3f3f3 | primary icons
$icon-02 | Gray 70 / #565656 | same as white | same as G90 | G30 / #BEBEBE | secondary icon colordecorative icons
$field-01 | Gray 10 / #F3F3F3 | White / #FFFFFF | G90 / #282828 | G80 / #3D3D3D | primary input field colorfields on secondary background
$field-02 | White / #FFFFFF | Gray 10 / #F3F3F3 | G80 / #3D3D3D | G70 / #565656 | Secondary input field color fields on secondary backgrounds
$inverse-01 | White / #FFFFFF | same as white | G100 / #171717 | G100 / #171717 | Inverse text inverse icon
$inverse-02 | Gray 80 / # 3d3d3d | same as white | G10 / #f3f3f3 | G10 / #f3f3f3 | High contrast backgroundsHigh contrast elements
$support-01 | Red 60 / #da1e28 | same as white | Red 50 / #FB4B53 | Red 50 / #FB4B53 | ErrorDanger
$support-02 | Green 60 / #198038 | same as white | Green 50 / #24A148 | Green 50 / #24A148 | Success
$support-03 | Yellow / #FDD13A | same as white | Yellow / #FDD13A | Yellow / #FDD13A | Warning
$support-04 | Blue 70 / #054ada | same as white | Blue 50 / #408BFC | Blue 50 / #408BFC | Informationalloading
$overlay-01 | Gray 100 (#171717) @ 50% | same as white | same as G90 | Gray 100 (#171717) @ 70% | Dark background overlay
$overlay-02 |   |   |   |   |  

### Interactive States Tokens

Token | White Theme | G10 Theme | G100 Theme | G90 Theme | Usage
-- | -- | -- | -- | -- | --
$focus | Blue 60 / #0062ff | same as white | same as G90 | White / #FFFFFF | Focus borderFocus underline
$hover-primary | Blue 60 Hover / #0353E9 | same as white | same as white | same as white | Hover color for interactive-01
$active-primary | Blue 80 / #0530ad | same as white | same as white | same as white | Active color for interactive-01
$hover-primary-text | Blue 70 / #054ada | same as white | same as white | same as white | Text + icon hover color for brand-01
$hover-secondary | Gray 80 hover /#4c4c4c | same as white | same as G90 | Gray 60 hover /#606060 | Hover for interactive-02Secondary button hover
$active-secondary | Gray 60 / #6f6f6f | same as white | same as G90 | Gray 80 / #3D3D3D | active color of $interactive-02Secondary button active
$hover-tertiary | Blue 60 Hover / #0353E9 | same as white | same as G90 | G10 / F3F3F3 | Hover state of tertiary button
$active-tertiary | Blue 80 / #0530AD | same as white | same as G90 | G30 / BEBEBE | active state of tertiary button
$hover-ui | Gray 10 Hover / #e5e5e5e | same as white | Gray 90 Hover / #353535 | Gray 80 Hover / #4C4C4C | hover white elementshover Gray elementshover transparent elements
$active-ui | Gray 30 / #bebebe | same as white | Gray 70 / #565656 | Gray 60 / #6F6F6F | Active background color for ui-01
$selected-ui | Gray 20 / #dcdcdc | same as white | Gray 80 / #3D3D3D | Gray 70 / #565656 | selected state
$hover-selected-ui | Gray 20 Hover / #CACACA | same as white | Gray 80 Hover / #4C4C4C | Gray 70 Hover / #656565 | data table selected row hover
$hover-danger | Red 60 Hover / #ba1b23 | same as white | same as white | same as white | Support-01 hover
$active-danger | Red 80 / #750e13 | same as white | same as white | same as white | Active color for support-01
$hover-row | Gray 10 hover / #e5e5e5 | same as white | Gray 90 Hover / #353535 | Gray 80 Hover / #4C4C4C | Row hover
$visted-link | Purple 60 / #8a3ffc | same as white | same as G90 | Purple 40 / #BB8EFF | Visited state for link
$disabled-01 | Gray 10 / #f3f3f3 | White / #ffffff | G90 / #282828 | G80 / #3D3D3D | disabled fields backgrounddisabled backgroundsdisabled border
$disabled-02 | Gray 30 / #bebebe | same as white | G80 / #3D3D3D | G70 / #565656 | disabled elements on $disabled-01 (Gray 10)disabled label on $disabled-01 (Gray 10)disabled text on $disabled-01 (Gray 10)disabled icons on $disabled-01 (Gray 10)disabled borderdisabled background
$disabled-03 | Gray 50 / #8c8c8c | same as white | G60 / #6F6F6F | G50 / #8C8C8C | disabled text on $disabled-02 (Gray 30)disabled icon on $disabled-02 (Gray 30)
