### ISSUE TITLE
Motion audit on components

### ISSUE THREAD

**Issue by shixiedesign** [IBM/carbon-elements#56]
Audit all 30 components planned for Carbon X for basic motion design. Basic motion design would include easing curve and fixed duration for a single transition and back (eg. open & close of a modal).

**Comment by shixiedesign** [comment]
Hi @aledavila @jnm2377 after audit, here are some basic motions for components that can be "easy-wins" for Carbon X release. Most of below falls into some kind of button/field hover and click category. Ideally we can build 1 animation and just call it whenever something behaves like a button. 

- [ ] Accordion hover, opening and closing
- [ ] Button hover & click 
- [ ] Dropdown hover, opening and closing
- [ ] Link hover & click
- [ ] Modal opening and closing, close button hover & click
- [ ] Notification opening and closing, close button hover & click
- [ ] Number input hover
- [ ] Overflow menu opening and closing
- [ ] Progress indicator state transition, hover & click
- [ ] Search hover and click
- [ ] Slider hover and click
- [ ] Structured list hover and click
- [ ] Tab hover and click
- [ ] Text input hover and click
- [ ] Toggle toggling
- [ ] Tooltip appearing and disappearing

**Comment by asudoh** [comment]
Weighing in - Great to have some technical study to see if the motions can be achieved solely by CSS. In our earlier work the developer found that JavaScript was absolutely necessary for some motions, which raised concerns wrt added complexity and performance. But as @shixiedesign implied, great to have some motions that would be easy wins!

**Comment by shixiedesign** [comment]
Moving on to next step: 
Implementing the motion to components. issue: https://github.com/IBM/carbon-components/issues/1433
