### ISSUE TITLE
Add @carbon/motion package with timing information

### ISSUE THREAD

**Issue by joshblack** [IBM/carbon-elements#65]
This issue is for creating the `@carbon/motion` package with SCSS and JS support for easing curves for components. Will need the values from @shixiedesign when she has the chance!

**Comment by shixiedesign** [comment]
Easing | Productive | Expressive
-- | -- | --
Standard easing | cubic-bezier(0.2, 0, 0.38, 0.9) | cubic-bezier(0.4, 0.14, 0.3, 1)
Entrance easing | cubic-bezier(0, 0, 0.38, 0.9) | cubic-bezier(0, 0, 0.3, 1)
Exit easing | cubic-bezier(0.2, 0, 1, 0.9) | cubic-bezier(0.4, 0.14, 1, 1)
