### ISSUE TITLE
Aligned type in Grid examples

### ISSUE THREAD

**Issue by qqpin** [IBM/carbon-elements#68]
Small, Medium, Large, X-Large, and Max should align with "Basic example"
![screen shot 2018-11-14 at 11 52 52 am](https://user-images.githubusercontent.com/14185008/48499029-80e87a80-e805-11e8-812e-8cccd638afec.png)

"Padding example" should align with Small, Medium, Large, X-Large, and Max
![screen shot 2018-11-14 at 12 04 37 pm](https://user-images.githubusercontent.com/14185008/48499079-96f63b00-e805-11e8-8df0-84b48d1b7da4.png)

Aspect Ratio, description, 1x1 and 4x3 should have 16px padding-left.
![screen shot 2018-11-14 at 12 04 32 pm](https://user-images.githubusercontent.com/14185008/48499118-affeec00-e805-11e8-8249-dda89fdf85a6.png)

**Comment by joshblack** [comment]
Thanks for this @qqpin! Seems like it was a bug in our auto col classes 😄 will fix in a PR soon!
