### ISSUE TITLE
Tabs (Dropdown Issue) - experimental component (feedback from review)

### ISSUE THREAD

**Issue by jeanservaas** [IBM/carbon-elements#78]
When Tabs component reverts to Dropdown at Md breakpoint:

- [ ] Make dropdown field Gray 20 on select (i.e. when menu is open) 
- [ ] Change field height of Dropdown to 40px and change menu item heights to 40px as well!
- [ ] Make sure hover states on open Dropdown menu will be #e5e5e5 (Gray 10 hover)
- [ ] Make sure hover state covers the rules (see file and also, structured list component); i.e. you don't want to see hover state AND rules at the same time
- [ ] Use chevron glyph (can ask @joshblack if you have trouble finding) for icon
- [ ] Position chevron 16px from the right edge of the dropdown
 

[Drop_down_Specs_revised.png](https://images.zenhubusercontent.com/5b96e742f28d730b01a470c0/43694f63-23e1-4192-aab8-d9bad950de3e)

**Comment by jnm2377** [comment]
Opened new issue in correct repo: https://github.com/IBM/carbon-components/issues/1451
