### ISSUE TITLE
Experimental motion package rebuild

### ISSUE THREAD

**Issue by shinytoyrobots** [IBM/carbon-elements#9]
## Experimental motion codebase and package fix and review

> The experimental motion package codebase build system is broken

> It also needs code review 

> https://github.com/ibm/motion

**Comment by aagonzales** [comment]
@dinaerdianinque

**Comment by joshblack** [comment]
@shixiedesign I think the plan is to bring over: https://github.com/IBM/motion as a sub-package, will check with Wonil if that's okay.

**Comment by joshblack** [comment]
Going to close this since I think we're just going to put out some easing curves in SCSS versus doing a full rebuild since some of the thinking in the current package might not represent the final state of things 👍
