### ISSUE TITLE
Create `@carbon/elements` entrypoint 

### ISSUE THREAD

**Issue by joshblack** [IBM/carbon-elements#98]
A nice enhancement would be to bring all of packages together as a single `@carbon/elements` package that might help as an alternative entrypoint for folks so they don't have to download every dependency that they need when they want to use most of what is provided in this project. This package would most likely include:

- Colors
- Motion
- Type
- Layout / Grid

**Comment by jendowns** [comment]
Just wanted to +1 this as an enhancement we would really love to see 🎉

**Comment by joshblack** [comment]
Always open for contributions @jendowns! 😉 haha. Especially for grid!
